#!/usr/bin/env python3
"""Explicit desktop onboarding; Router remains the policy and delivery authority.

Secrets travel over stdin to Secret Service, never through argv, files or QML
results. Only the exact starter policy or our unchanged owned policy is edited.
"""
import argparse
import fcntl
import hashlib
import json
import os
from pathlib import Path
import re
import selectors
import signal
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
import uuid

LIMIT = 1024 * 1024
APP = "io.github.asdecided.wayfinder"
SECRET_TOOL = "/usr/bin/secret-tool"
API = "https://api.openai.com/v1"
STARTER = '''# Generated by wayfinder-router init (preset: local).
[routing]
threshold = 1.0

[gateway]
offline = true

[gateway.models.local]
base_url = "http://localhost:11434/v1"
model = "llama3.1"
cost_per_1k = 0.0
'''


class SetupError(Exception):
    pass


def run(args, data=None, timeout=20, accepted=(0,)):
    """Bound subprocess time and each output pipe; never expose child errors."""
    try:
        child = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                 stderr=subprocess.PIPE, start_new_session=True)
    except OSError:
        raise SetupError("Required program could not start. Check the installation.") from None
    deadline = time.monotonic() + timeout
    out = bytearray()
    err = bytearray()
    try:
        with selectors.DefaultSelector() as selector:
            for stream, result in [(child.stdout, out), (child.stderr, err)]:
                os.set_blocking(stream.fileno(), False)
                selector.register(stream, selectors.EVENT_READ, result)
            # Inputs are at most 8 KiB, below the pipe capacity.
            if data:
                child.stdin.write(data)
                child.stdin.flush()
            child.stdin.close()
            while selector.get_map():
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    raise SetupError("Operation timed out. Unlock the desktop keyring and retry.")
                for key, _ in selector.select(min(remaining, 0.2)):
                    chunk = os.read(key.fd, 4096)
                    if not chunk:
                        selector.unregister(key.fileobj)
                    else:
                        key.data.extend(chunk)
                        if len(key.data) > LIMIT:
                            raise SetupError("Operation returned too much data.")
            code = child.wait(timeout=max(0.01, deadline - time.monotonic()))
        if code not in accepted:
            raise SetupError("Operation failed. Check service status or unlock the desktop keyring, then retry.")
        return bytes(out)
    except (subprocess.TimeoutExpired, BrokenPipeError):
        raise SetupError("Operation could not complete. Retry after checking the service and keyring.") from None
    finally:
        if child.poll() is None:
            os.killpg(child.pid, 9)
        child.wait()
        child.stdout.close()
        child.stderr.close()
        out[:] = b"\0" * len(out)
        err[:] = b"\0" * len(err)


class NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, *args, **kwargs):
        return None


def request(url, key=None, body=None):
    headers = {"Content-Type": "application/json"}
    if key:
        headers["Authorization"] = "Bearer " + key
    data = None if body is None else json.dumps(body).encode()
    try:
        # No ambient proxy can intercept loopback verification or receive keys.
        opener = urllib.request.build_opener(urllib.request.ProxyHandler({}), NoRedirect())
        with opener.open(urllib.request.Request(url, data=data, headers=headers), timeout=25) as response:
            raw = response.read(LIMIT + 1)
            request_id = response.headers.get("x-wayfinder-router-request-id")
        if len(raw) > LIMIT:
            raise SetupError("Response exceeded the setup limit.")
        result = json.loads(raw)
        if not isinstance(result, dict):
            raise SetupError("Provider returned an invalid response.")
        if request_id:
            result["_router_request_id"] = request_id
        return result
    except urllib.error.HTTPError as error:
        messages = {401: "API key rejected. Replace it and try again.",
                    403: "This key does not have permission for this model.",
                    404: "Model unavailable. Refresh models and choose again.",
                    429: "Rate or quota limit reached. Check API billing and retry.",
                    400: "This model did not accept the chat test. Choose a compatible chat model."}
        raise SetupError(messages.get(error.code, "Request failed. Check provider availability and retry.")) from None
    except (OSError, ValueError, urllib.error.URLError):
        raise SetupError("Could not reach the provider or Router. Check the connection and retry.") from None


def digest(text):
    return hashlib.sha256(text.encode()).hexdigest()


def read(path):
    if path.is_symlink() or not path.is_file() or path.stat().st_size > LIMIT:
        raise SetupError("Configuration or setup state is missing, oversized, or symlinked. No changes made.")
    return path.read_text()


def atomic(path, text):
    if path.is_symlink():
        raise SetupError("Refusing to replace a symlink.")
    fd, name = tempfile.mkstemp(prefix=".setup-", dir=path.parent)
    try:
        with os.fdopen(fd, "w") as stream:
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(name, path)
        directory = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
    finally:
        if os.path.exists(name):
            os.unlink(name)


def policy(model, item):
    if not re.fullmatch(r"[A-Za-z0-9_.:/-]{1,256}", model):
        raise SetupError("Invalid model identifier.")
    if not re.fullmatch(r"[a-f0-9]{32}", item):
        raise SetupError("Invalid credential reference.")
    return f'''# Owned by Wayfinder Omarchy guided setup. Hosted routing explicitly selected.
[[routing.tiers]]
min_score = 0.0
model = "openai"

[gateway]
offline = false

[gateway.models.openai]
provider = "openai-compatible"
base_url = "{API}"
model = "{model}"
api_key_env = "WAYFINDER_DESKTOP_OPENAI_{item}"
api_key_cmd = "{SECRET_TOOL} lookup application {APP} credential {item}"
'''


class Onboarding:
    def __init__(self, router, config, endpoint):
        self.router = router
        self.config = Path(config)
        default = Path(os.environ.get("XDG_CONFIG_HOME", str(Path.home() / ".config"))) / "wayfinder/wayfinder-router.toml"
        if self.config != default or not self.config.is_absolute() or self.config.resolve() != self.config:
            raise SetupError("Guided setup preserves custom policy paths. Use the configuration guide for this policy.")
        if not re.fullmatch(r"http://127\.0\.0\.1:([0-9]{1,5})", endpoint):
            raise SetupError("Guided setup requires a 127.0.0.1 HTTP endpoint.")
        self.port = int(endpoint.rsplit(":", 1)[1])
        if not 1 <= self.port <= 65535:
            raise SetupError("Invalid Router port.")
        self.endpoint = endpoint
        self.directory = self.config.parent / "omarchy-setup"
        if self.directory.is_symlink():
            raise SetupError("Setup directory must not be a symlink.")
        self.directory.mkdir(mode=0o700, exist_ok=True)
        self.path = self.directory / "state.json"

    def load(self):
        if not self.path.exists():
            return {}
        state = json.loads(read(self.path))
        if state.get("schema") != 1 or not re.fullmatch(r"[a-f0-9]{32}", state.get("item", "")):
            raise SetupError("Setup state is invalid. Existing configuration was preserved.")
        return state

    def save(self, state):
        atomic(self.path, json.dumps(state))

    def unchanged(self, state):
        current = read(self.config)
        allowed = [digest(STARTER)]
        if state.get("model"):
            allowed.append(digest(policy(state["model"], state["item"])))
        if digest(current) not in allowed:
            raise SetupError("This policy has custom changes. Guided setup will not overwrite them.")
        return current

    def secret(self, action, item, value=None):
        if not Path(SECRET_TOOL).is_file():
            raise SetupError("Install libsecret and a Secret Service keyring (for example gnome-keyring), then unlock it and retry. Keys are never saved to a plain-text fallback.")
        args = [SECRET_TOOL, action]
        if action == "store":
            args += ["--label=Wayfinder OpenAI"]
        if action == "search":
            args += ["--all", "--unlock"]
        args += ["application", APP, "credential", item]
        output = run(args, value.encode() if value is not None else None)
        # Search output can include a secret; retain only presence, never render it.
        return bool(output) if action == "search" else output.decode().strip()

    def status(self):
        state = self.load()
        self.unchanged(state)
        return {"stage": state.get("stage", "provider"), "model": state.get("model", ""),
                "models": state.get("models", []), "keyringInstalled": Path(SECRET_TOOL).is_file(),
                "verifiedAt": state.get("verifiedAt"), "owned": bool(state)}

    def discover(self, value):
        state = self.load()
        self.unchanged(state)
        if state and state.get("stage") != "saving-key":
            raise SetupError("Disconnect the existing setup first to replace its key. Your active setup is preserved.")
        if not 1 <= len(value) <= 4096 or any(ord(c) < 33 or ord(c) > 126 for c in value):
            raise SetupError("Enter a valid API key.")
        result = request(API + "/models", value)
        models = sorted({row["id"] for row in result.get("data", []) if isinstance(row, dict)
                         and isinstance(row.get("id"), str)
                         and re.fullmatch(r"[A-Za-z0-9_.:/-]{1,256}", row["id"])})
        if not models or len(models) > 2000:
            raise SetupError("No usable model list was returned for this key.")
        state = {"schema": 1, "stage": "saving-key", "item": state.get("item", uuid.uuid4().hex),
                 "models": models}
        # Journal identity first, allowing explicit cleanup after interruption.
        self.save(state)
        self.secret("store", state["item"], value)
        state["stage"] = "model"
        self.save(state)
        return self.status()

    def refresh_models(self):
        state = self.load()
        self.unchanged(state)
        if not state:
            raise SetupError("Connect OpenAI first.")
        result = request(API + "/models", self.secret("lookup", state["item"]))
        models = sorted({r["id"] for r in result.get("data", []) if isinstance(r, dict)
                         and isinstance(r.get("id"), str)
                         and re.fullmatch(r"[A-Za-z0-9_.:/-]{1,256}", r["id"])})
        if not models or len(models) > 2000:
            raise SetupError("No usable model list returned.")
        state["models"] = models
        state.pop("verifiedAt", None)
        self.save(state)
        return self.status()

    def activate(self, model):
        state = self.load()
        current = self.unchanged(state)
        if state.get("stage") != "model" or model not in state.get("models", []):
            raise SetupError("Save a key and select a discovered model first.")
        candidate = policy(model, state["item"])
        stage = self.directory / "candidate.toml"
        atomic(stage, candidate)
        report = json.loads(run([self.router, "doctor", "--config", str(stage), "--json"], accepted=(0, 1)))
        if str(report.get("schema_version")) != "1" or report.get("destinations") != 1 or not any(
                check.get("id") == "config" and check.get("status") == "pass" for check in report.get("checks", [])):
            raise SetupError("The Router rejected the proposed policy.")
        if read(self.config) != current:
            raise SetupError("Policy changed during setup. No changes made.")
        state.update(stage="activating", model=model)
        self.save(state)
        atomic(self.config, candidate)
        self.restart()
        state["stage"] = "test"
        self.save(state)
        return self.status()

    def restart(self):
        run([self.router, "service", "install", "--config", str(self.config),
             "--host", "127.0.0.1", "--port", str(self.port)])
        run(["systemctl", "--user", "restart", "wayfinder-router.service"])

    def test(self):
        state = self.load()
        current = self.unchanged(state)
        if not state.get("model") or current != policy(state["model"], state["item"]):
            raise SetupError("Activate your selected model first.")
        # Clear previous proof before any network operation, including retries.
        state.pop("verifiedAt", None)
        state["stage"] = "test"
        self.save(state)
        health = request(self.endpoint + "/healthz")
        if health.get("offline") or health.get("status") != "ok":
            raise SetupError("Router not ready for hosted requests. Unlock the keyring and repair the service.")
        models = request(self.endpoint + "/router/models")
        # Verify the running process loaded this policy, not another service.
        entries = models.get("models", [])
        if isinstance(entries, dict):
            entries = [dict(v, name=k) for k, v in entries.items()]
        if not isinstance(entries, list) or models.get("dry_run") or not any(isinstance(m, dict) and m.get("name") == "openai" and m.get("model") == state["model"]
                and m.get("endpoint") == API and m.get("key_ok") is True for m in entries):
            raise SetupError("Running Router has a different model. Repair the service and retry.")
        result = request(self.endpoint + "/v1/chat/completions", "wayfinder-local", {
            "model": "openai", "messages": [{"role": "user", "content": "Reply with the single word connected. Test ID: " + uuid.uuid4().hex}],
            "max_completion_tokens": 256, "stream": False})
        choices = result.get("choices", [])
        message = choices[0].get("message") if isinstance(choices, list) and choices and isinstance(choices[0], dict) else None
        if not isinstance(message, dict) or not isinstance(message.get("content"), str) or not message["content"].strip():
            raise SetupError("The model returned no text within the test limit. Choose another chat model or retry.")
        receipt_id = result.get("_router_request_id")
        receipts = request(self.endpoint + "/router/recent?limit=8").get("recent", [])
        if not receipt_id or not isinstance(receipts, list) or not any(isinstance(r, dict) and r.get("request_id") == receipt_id and r.get("served_by") == "openai"
                                    and r.get("http_status") == 200 and r.get("outcome") == "succeeded"
                                    for r in receipts):
            raise SetupError("A response arrived but its successful Router receipt was not verified. Retry the test.")
        state.update(stage="verified", verifiedAt=int(time.time()))
        self.save(state)
        return self.status()

    def repair(self):
        state = self.load()
        current = self.unchanged(state)
        state.pop("verifiedAt", None)
        if state.get("model"):
            state["stage"] = "test" if current == policy(state["model"], state["item"]) else "model"
            if state["stage"] == "model":
                state.pop("model", None)
            self.save(state)
        self.restart()
        return self.status()

    def disconnect(self):
        state = self.load()
        self.unchanged(state)
        if not state:
            return self.status()
        # Stop first: the Router may hold a resolved key in memory.
        run(["systemctl", "--user", "stop", "wayfinder-router.service"])
        state["stage"] = "disconnecting"
        state.pop("verifiedAt", None)
        self.save(state)
        atomic(self.config, STARTER)
        # libsecret clear removes only unlocked items and returns 1 for no match.
        # Search unlocks matching items first; absence is successful/idempotent.
        if self.secret("search", state["item"]):
            self.secret("clear", state["item"])
        if self.secret("search", state["item"]):
            raise SetupError("Credential removal was not confirmed. Unlock the keyring and retry disconnect.")
        self.path.unlink()
        self.restart()
        return self.status()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=["status", "discover", "refresh-models", "activate", "test", "repair", "disconnect"])
    parser.add_argument("--router", required=True)
    parser.add_argument("--config", required=True)
    parser.add_argument("--endpoint", required=True)
    parser.add_argument("--model", default="")
    args = parser.parse_args()
    try:
        def interrupted(signum, frame):
            raise SetupError("Operation cancelled or timed out. Recheck setup; repair or disconnect any interrupted activation.")
        signal.signal(signal.SIGTERM, interrupted)
        signal.signal(signal.SIGALRM, interrupted)
        signal.alarm(90)
        setup = Onboarding(args.router, args.config, args.endpoint)
        lock = setup.directory / "lock"
        fd = os.open(lock, os.O_CREAT | os.O_RDWR | os.O_NOFOLLOW, 0o600)
        with os.fdopen(fd, "w") as stream:
            try:
                fcntl.flock(stream, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except BlockingIOError:
                raise SetupError("Another setup operation is running.") from None
            if args.action == "discover":
                value = sys.stdin.buffer.readline(4098).decode().rstrip("\n")
                result = setup.discover(value)
            elif args.action == "activate":
                result = setup.activate(args.model)
            else:
                result = getattr(setup, args.action.replace("-", "_"))()
        print(json.dumps({"ok": True, **result}))
        return 0
    except SetupError as error:
        print(json.dumps({"ok": False, "error": str(error)}))
    except (OSError, ValueError, KeyError, TypeError):
        print(json.dumps({"ok": False, "error": "Setup could not read its state. Existing custom files were preserved."}))
    return 1


if __name__ == "__main__":
    sys.exit(main())
